name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Check TypeScript compilation
      run: npm run build
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/
        retention-days: 1

  validate-package:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build package
      run: npm run build
    
    - name: Test package can be packed
      run: npm pack
    
    - name: Validate package contents
      run: |
        echo "Package contents:"
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz
        
        echo "\nChecking required files..."
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz | grep -q "package/dist/" || (echo "❌ Missing dist/ directory" && exit 1)
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz | grep -q "package/package.json" || (echo "❌ Missing package.json" && exit 1)
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz | grep -q "package/README.md" || (echo "❌ Missing README.md" && exit 1)
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz | grep -q "package/LICENSE" || (echo "❌ Missing LICENSE" && exit 1)
        tar -tzf n8n-nodes-evolution-api-tool-*.tgz | grep -q "package/index.js" || (echo "❌ Missing index.js" && exit 1)
        
        echo "✅ Package validation passed!"
